ALTER TABLE PUBLIC.RECIPE DROP COLUMN ingredients;

CREATE CACHED TABLE PUBLIC.INGREDIENT(
  id BIGINT NOT NULL,
  modificationCounter INTEGER NOT NULL,
  name VARCHAR(255)
);
CREATE CACHED TABLE PUBLIC.RECIPE_INGREDIENT(
  id BIGINT NOT NULL,
  modificationCounter INTEGER NOT NULL,
  pk_recipe BIGINT NOT NULL,
  pk_ingredient BIGINT NOT NULL,
  amount DOUBLE,
  measuringUnit VARCHAR(255),
  position INTEGER
);

ALTER TABLE PUBLIC.INGREDIENT ADD CONSTRAINT PUBLIC.PK_INGREDIENT PRIMARY KEY(id);

ALTER TABLE PUBLIC.RECIPE_INGREDIENT ADD CONSTRAINT PUBLIC.PK_RECIPE_INGREDIENT PRIMARY KEY(id);
ALTER TABLE PUBLIC.RECIPE_INGREDIENT ADD CONSTRAINT PUBLIC.FK_RECIPE FOREIGN KEY(pk_recipe) REFERENCES PUBLIC.RECIPE(id) NOCHECK;
ALTER TABLE PUBLIC.RECIPE_INGREDIENT ADD CONSTRAINT PUBLIC.FK_INGREDIENT FOREIGN KEY(pk_ingredient) REFERENCES PUBLIC.INGREDIENT(id) NOCHECK;
